all: cat date ls mkdir rm suiishell

cat: cat.c
	gcc cat.c -o cat

date: date.c
	gcc date.c -o date

ls: ls.c
	gcc ls.c -o ls

mkdir: mkdir.c
	gcc mkdir.c -o mkdir

rm: rm.c
	gcc rm.c -o rm

suiishell: suiishell.c
	gcc suiishell.c -o suiishell
